cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #8 & #9 first CFTs

cloudformation-senzing-basic.yaml
=> #32 updated paths

cloudformation-senzing-basic.yaml
=> #35 updated to include wss config

cloudformation-senzing-basic.yaml
=> #34 updated with all the latest image versions

cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> Issue 38.ron.0

docs/details.md
=> #42 updated CFT URLs

cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> updated lambda function to produce better error messages

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> updated change log and version

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #62 extended subnet size

.github/workflows/copy-to-s3.yaml
Issue number: #12 
Add some automation to copy released CFTs to S3 when a release is published
Reviewers: Please double check paths.
=> Adding workflow to copy CFTs to S3 when a release is published

cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
Issue number: #66 & #68
???
???
=> #66 added autovacuum_max_workers=5 parameter

CHANGELOG.md, cloudformation-senzing-basic.yaml
=> #69 updated yum container version

CHANGELOG.md, cloudformation-senzing-basic.yaml
=> Issue 72.ron.0

CHANGELOG.md, cloudformation-senzing-basic.yaml
=> #75 updated image versions

CHANGELOG.md, cloudformation-senzing-basic-v2.yaml, cloudformation-senzing-database-v2.yaml, docs/details.md
Issue number: #81 #79 #78
???
???
=> #81 updated for 3.0.0

CHANGELOG.md, cloudformation-senzing-basic.yaml
=> #85 updated release number

CONTRIBUTING.md, cloudformation-senzing-basic-v2.yaml, cloudformation-senzing-basic.yaml, docs/details.md
=> #80 Migrate from master to main

CHANGELOG.md, README.md, cloudformation-senzing-basic.yaml
=> #89 updated resource names

README.md
=> #91 updated readme

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #94 added images to outputs

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #93 updated senzing and docker image versions

CHANGELOG.md, cloudformation-senzing-database.yaml
=> #99 added SecondsBeforeTimeout setting

README.md
=> #53 Add information on supported regions

docs/examples/CFn_Policy3.json
=> #64 updated example policy

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
Issue number: #104 #105
???
???
=> Issue 104.ron.0

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
Issue number: #108 #109 #98 #107
Brings marketplace offering into sync with recent database and basic changes.
???
=> Issue 108.ron.0

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> Issue 111.ron.0

README.md
=> #113 updated README

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> Issue 115.ron.0

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #117 updated to senzing 3.3.1

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> Issue 119.ron.0

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
Issue number: #125 #126 
???
???
=> #125 updated to senzing 3.4.0 and updated datbase parameters

CHANGELOG.md, cloudformation-senzing-basic.yaml
=> #130 updated updated consumer policy

.github/workflows/copy-to-s3.yaml
=> Issue 134.jadair.1

.gitignore, CHANGELOG.md, README.md, docs/details.md, docs/errors.md
=> #136 Update links

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #138 updated docker images, change log and versioning for release

CHANGELOG.md, cloudformation-senzing-basic.yaml, cloudformation-senzing-database.yaml
=> #142 update docker images and senzing version

.github/dependabot.yml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml
Issue number: senzing-factory/build-resources#91
=> senzing-factory/build-resources#91 fix dependabot project status

.github/linters/.yaml-lint.yml, .github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/copy-to-s3.yaml, .github/workflows/lint-workflows.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add linting
